default_language_version:
    python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: ["max-size=10M"]
  - repo: https://github.com/pyca/isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
        args: ["--line-length=120"]
  - repo: https://github.com/pyca/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3.9
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        args: ["--namespace-packages"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [
          "--max-line-length=120",
          "--disable=C0103",
          "--disable=E0401",
          "--disable=W1514",
          "--disable=logging-fstring-interpolation",
          "--disable=anomalous-backslash-in-string",
        ]